version: '3.7'


services:

  web:

   build: .
   
   ports:
    - "8000:8000"
   
   depends_on: 
    - db

   command: python /code/manage.py runserver 0.0.0.0:8000

   volumes:
    - .:/code

  db:
    image: postgres:11

